/*
 * Instrument names for LA-based modules 
 */

/*
 *  Copyright (C) 1997,1998   Satoshi Nishimura
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

AcouPiano1 = 'prog(1)'
AcouPiano2 = 'prog(2)'
AcouPiano3 = 'prog(3)'
ElecPiano1 = 'prog(4)'
ElecPiano2 = 'prog(5)'
ElecPiano3 = 'prog(6)'
ElecPiano4 = 'prog(7)'
HonkyTonk  = 'prog(8)'
ElecOrg1   = 'prog(9)'
ElecOrg2   = 'prog(10)'
ElecOrg3   = 'prog(11)'
ElecOrg4   = 'prog(12)'
PipeOrg1   = 'prog(13)'
PipeOrg2   = 'prog(14)'
PipeOrg3   = 'prog(15)'
Accordion  = 'prog(16)'
Harpsi1    = 'prog(17)'
Harpsi2    = 'prog(18)'
Harpsi3    = 'prog(19)'
Clavi1     = 'prog(20)'
Clavi2     = 'prog(21)'
Clavi3     = 'prog(22)'
Celesta1   = 'prog(23)'
Celesta2   = 'prog(24)'
SynBrass1  = 'prog(25)'
SynBrass2  = 'prog(26)'
SynBrass3  = 'prog(27)'
SynBrass4  = 'prog(28)'
SynBass1   = 'prog(29)'
SynBass2   = 'prog(30)'
SynBass3   = 'prog(31)'
SynBass4   = 'prog(32)'
Fantasy    = 'prog(33)'
HarmoPan   = 'prog(34)'
Chorale    = 'prog(35)'
Glasses    = 'prog(36)'
SoundTrack = 'prog(37)'
Atmosphere = 'prog(38)'
WarmBell   = 'prog(39)'
FunnyVox   = 'prog(40)'
EchoBell   = 'prog(41)'
IceRain    = 'prog(42)'
Oboe2001   = 'prog(43)'
EchoPan    = 'prog(44)'
DoctorSolo = 'prog(45)'
Schooldaze = 'prog(46)'
Bellsinger = 'prog(47)'
SquareWave = 'prog(48)'
StrSect1   = 'prog(49)'
StrSect2   = 'prog(50)'
StrSect3   = 'prog(51)'
Pizzicato  = 'prog(52)'
Violin1    = 'prog(53)'
Violin2    = 'prog(54)'
Cello1     = 'prog(55)'
Cello2     = 'prog(56)'
Contrabass = 'prog(57)'
Harp1      = 'prog(58)'
Harp2      = 'prog(59)'
Guitar1    = 'prog(60)'
Guitar2    = 'prog(61)'
ElecGtr1   = 'prog(62)'
ElecGtr2   = 'prog(63)'
Sitar      = 'prog(64)'
AcouBass1  = 'prog(65)'
AcouBass2  = 'prog(66)'
ElecBass1  = 'prog(67)'
ElecBass2  = 'prog(68)'
SlapBass1  = 'prog(69)'
SlapBass2  = 'prog(70)'
Fretless1  = 'prog(71)'
Fretless2  = 'prog(72)'
Flute1     = 'prog(73)'
Flute2     = 'prog(74)'
Piccolo1   = 'prog(75)'
Piccolo2   = 'prog(76)'
Recorder   = 'prog(77)'
PanPipes   = 'prog(78)'
Sax1       = 'prog(79)'
Sax2       = 'prog(80)'
Sax3       = 'prog(81)'
Sax4       = 'prog(82)'
Clarinet1  = 'prog(83)'
Clarinet2  = 'prog(84)'
Oboe       = 'prog(85)'
EnglHorn   = 'prog(86)'
Bassoon    = 'prog(87)'
Harmonica  = 'prog(88)'
Trumpet1   = 'prog(89)'
Trumpet2   = 'prog(90)'
Trombone1  = 'prog(91)'
Trombone2  = 'prog(92)'
FrHorn1    = 'prog(93)'
FrHorn2    = 'prog(94)'
Tuba       = 'prog(95)'
BrsSect1   = 'prog(96)'
BrsSect2   = 'prog(97)'
Vibe1      = 'prog(98)'
Vibe2      = 'prog(99)'
SynMallet  = 'prog(100)'
WindBell   = 'prog(101)'
Glock      = 'prog(102)'
TubeBell   = 'prog(103)'
Xylophone  = 'prog(104)'
Marimba    = 'prog(105)'
Koto       = 'prog(106)'
Sho        = 'prog(107)'
Shakuhachi = 'prog(108)'
Whistle1   = 'prog(109)'
Whistle2   = 'prog(110)'
BottleBlow = 'prog(111)'
BreathPipe = 'prog(112)'
Timpani    = 'prog(113)'
MelodicTom = 'prog(114)'
DeepSnare  = 'prog(115)'
ElecPrec1  = 'prog(116)'
ElecPerc2  = 'prog(117)'
Taiko      = 'prog(118)'
TaikoRim   = 'prog(119)'
Cymbal     = 'prog(120)'
Castanets  = 'prog(121)'
Triangle   = 'prog(122)'
OrcheHit   = 'prog(123)'
Telephone  = 'prog(124)'
BirdTweet  = 'prog(125)'
OneNoteJam = 'prog(126)'
WaterBells = 'prog(127)'
JungleTune = 'prog(128)'

