/*
 * PMML: A Compiler for the Practical Music Macro Language
 *
 * table.c: table defining a handler function etc. for each token type
 */

/*
 *  Copyright (C) 1997,1998   Satoshi Nishimura
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

#include <stdio.h>
#include "pmml.h"

int op_uminus(), op_lognot(), op_bitnot(), op_mult(), op_div(),
    op_rem(), op_add(), op_sub(), op_shr(), op_shl(),
    op_lt(), op_lteq(), op_gt(), op_gteq(), op_eq(),
    op_neq(), op_bitand(), op_xor(), op_bitor(), op_logand(),
    op_logor(), op_cond(), op_serror(), op_fatal();

int identifier(), array_subscript(), strong_token_list(),
    number_sign(), dollar_sign(), at_mark(),
    do_def(), do_undef(), do_eval(), do_evalstr(), do_if(), do_switch(),
    do_while(), do_for(), do_foreach(), do_repeat(), do_break(),
    end_for(), end_foreach(), end_while(), end_repeat(),
    do_append(), do_insert(), do_shift(), do_include(),
    do_null();

int do_pitch(), do_reg(), do_length(), do_octave(), 
    do_accent(), do_tshift(), do_defthread(), do_semicolon(),
    do_thread(), do_lbrace(), do_rbrace(), do_lbracket(),
    begin_of_named_thread(), end_of_named_thread(),
    do_rbracket(), do_sync(), end_of_block(), do_eof(), end_sync(),
    do_signal(), do_wait(), end_wait(), do_alt(), end_alt(),
    do_effclass(), do_effinst(), do_attach(),
    do_note_on(), do_note_off(), do_ctrl(),
    do_cont_ctrl(), do_excl(), do_seqno(),
    do_text(), do_meta(), do_smpte(),
    do_timesig(), do_keysig(), do_end(),
    do_load(), do_close(),
    do_defeff(), do_enable(),
    do_eff_etypes(), do_eff_chs(),
    do_ctrl_any(), do_ecode();

struct tok_table  tkinfo[] = {
/* 00: T_EOF      */  { F_C             ,    0,    0, do_eof },
/* 01: T_NUMBER   */  { F_OPD           ,    0,    0, NULL },
/* 02: T_RATIONAL */  { F_OPD|F_C       ,    0,    0, do_length },
/* 03: T_STRING   */  { F_OPD           ,    0,    0, NULL },
/* 04: T_ARRAY    */  { F_OPD|F_M       ,    0,    0, array_subscript },
/* 05: T_STOKENS  */  { F_OPD|F_TK      ,    0,    0, strong_token_list },
/* 06: T_WTOKENS  */  { 0               ,    0,    0, NULL },
/* 07: T_NIL	  */  { 0		,    0,    0, NULL },
/* 08: T_ID       */  { F_M             ,    0,    0, identifier },
/* 09: T_LOCALID  */  { F_M             ,    0,    0, identifier },
/* 0a: T_ISTREAM  */  { 0               ,    0,    0, NULL },
/* 0b: T_THREAD   */  { F_C             ,    0,    0, do_thread },
/* 0c: T_EFFCLASS */  { F_C             ,    0,    0, do_effclass },
/* 0d: T_EFFINST  */  { F_C             ,    0,    0, do_effinst },
/* 0e: T_PITCH    */  { F_OPD|F_C       ,    0,    0, do_pitch },
/* 0f: T_EFOR     */  { F_M|F_EOL       ,    0,    0, end_for },
/* 10: T_EFOREACH */  { F_M|F_EOL       ,    0,    0, end_foreach },
/* 11: T_EWHILE   */  { F_M|F_EOL       ,    0,    0, end_while },
/* 12: T_EREPEAT  */  { F_M|F_EOL       ,    0,    0, end_repeat },
/* 13: T_OCTAVE   */  { F_C             ,    0,    0, do_octave },
/* 14: T_TSHIFT   */  { F_C             ,    0,    0, do_tshift },
/* 15: T_ACCENT   */  { F_C             ,    0,    0, do_accent },
/* 16: T_EOB      */  { F_C             ,    0,    0, end_of_block },
/* 17: T_EOINIT   */  { 0               ,    0,    0, NULL },
/* 18: T_BOT      */  { F_C             ,    0,    0, begin_of_named_thread },
/* 19: T_EOT      */  { F_C             ,    0,    0, end_of_named_thread },
/* 1a: T_EOP      */  { F_C             ,    0,    0, end_of_block },
/* 1b: T_ESYNC    */  { F_C             ,    0,    0, end_sync },
/* 1c: T_EWAIT    */  { F_C             ,    0,    0, end_wait },
/* 1d: T_EALT     */  { F_C|F_EOL       ,    0,    0, end_alt },
/* 1e: 30         */  { 0               ,    0,    0, NULL },
/* 1f: 31         */  { 0               ,    0,    0, NULL },
/* 20: <sp>       */  { 0               ,    0,    0, NULL },
/* 21: !          */  { F_U|F_PU        ,   12,    0, op_lognot },
/* 22: "          */  { 0               ,    0,    0, NULL },
/* 23: #          */  { F_M             ,    0,    0, number_sign },
/* 24: $          */  { F_AG            ,    0,    0, dollar_sign },
/* 25: %          */  { F_B|F_PU        ,   11,    0, op_rem },
/* 26: &          */  { F_B|F_PU        ,    6,    0, op_bitand },
/* 27: '          */  { F_OPD           ,    0,    0, NULL },
/* 28: (          */  { F_PU            ,    0,    0, op_serror },
/* 29: )          */  { 0               ,    0,    0, op_fatal },
/* 2a: *          */  { F_B|F_PU        ,   11,    0, op_mult },
/* 2b: +          */  { F_B|F_PU        ,   10,    0, op_add },
/* 2c: ,          */  { 0               ,    0,    0, NULL },
/* 2d: -          */  { F_B|F_PU        ,   10,    0, op_sub },
/* 2e: .          */  { F_M             ,    0,    0, identifier },
/* 2f: /          */  { F_B|F_PU        ,   11,    0, op_div },
/* 30: 0          */  { 0               ,    0,    0, NULL },
/* 31: 1          */  { 0               ,    0,    0, NULL },
/* 32: 2          */  { 0               ,    0,    0, NULL },
/* 33: 3          */  { 0               ,    0,    0, NULL },
/* 34: 4          */  { 0               ,    0,    0, NULL },
/* 35: 5          */  { 0               ,    0,    0, NULL },
/* 36: 6          */  { 0               ,    0,    0, NULL },
/* 37: 7          */  { 0               ,    0,    0, NULL },
/* 38: 8          */  { 0               ,    0,    0, NULL },
/* 39: 9          */  { 0               ,    0,    0, NULL },
/* 3a: :          */  { F_T|F_PU|F_L    ,    1,    0, op_cond },
/* 3b: ;          */  { F_C             ,    0,    0, do_semicolon },
/* 3c: <          */  { F_B|F_PU        ,    8,    0, op_lt },
/* 3d: =          */  { 0               ,    0,    0, NULL },
/* 3e: >          */  { F_B|F_PU        ,    8,    0, op_gt },
/* 3f: ?          */  { F_T|F_PU|F_L    ,    1,    0, op_serror },
/* 40: @          */  { F_M             ,    0,    0, at_mark },
/* 41: T_GTEQ     */  { F_B|F_PU        ,    8,    0, op_gteq },
/* 42: T_LTEQ     */  { F_B|F_PU        ,    8,    0, op_lteq },
/* 43: T_LOGAND   */  { F_B|F_PU|F_L    ,    3,    0, op_logand },
/* 44: T_LOGOR    */  { F_B|F_PU|F_L    ,    2,    0, op_logor },
/* 45: T_EQ       */  { F_B|F_PU        ,    7,    0, op_eq },
/* 46: T_NEQ      */  { F_B|F_PU        ,    7,    0, op_neq },
/* 47: T_PLUSEQ   */  { F_CA            ,    0,    0, op_add },
/* 48: T_MINUSEQ  */  { F_CA            ,    0,    0, op_sub },
/* 49: T_MULTEQ   */  { F_CA            ,    0,    0, op_mult },
/* 4a: T_DIVEQ    */  { F_CA            ,    0,    0, op_div },
/* 4b: T_REMEQ    */  { F_CA            ,    0,    0, op_rem },
/* 4c: T_SHLEQ    */  { F_CA            ,    0,    0, op_shl },
/* 4d: T_SHREQ    */  { F_CA            ,    0,    0, op_shr },
/* 4e: T_ANDEQ    */  { F_CA            ,    0,    0, op_bitand },
/* 4f: T_XOREQ    */  { F_CA            ,    0,    0, op_xor },
/* 50: T_OREQ     */  { F_CA            ,    0,    0, op_bitor },
/* 51: T_DCOLON   */  { F_M             ,    0,    0, identifier },
/* 52: T_UMINUS   */  { F_U|F_PU        ,   12,    0, op_uminus },
/* 53: T_BOTTOM   */  { F_PU            ,    0,    0, op_fatal },
/* 54: T_ASUB     */  { 0               ,    0,    0, NULL },
/* 55: T_INITBLK  */  { 0               ,    0,    0, NULL },
/* 56: T_TRIEQ    */  { F_C             ,    0,    0, do_sync },
/* 57: T_DDOT     */  { F_M             ,    0,    0, identifier },
/* 58: T_TDOT     */  { F_M             ,    0,    0, identifier },
/* 59: Y          */  { 0               ,    0,    0, NULL },
/* 5a: Z          */  { 0               ,    0,    0, NULL },
/* 5b: [          */  { F_C             ,    0,    0, do_lbracket },
/* 5c: \          */  { 0               ,    0,    0, NULL },
/* 5d: ]          */  { F_C             ,    0,    0, do_rbracket },
/* 5e: ^          */  { 0               ,    0,    0, NULL },
/* 5f: _          */  { 0               ,    0,    0, NULL },
/* 60: `          */  { F_OPD           ,    0,    0, NULL },
/* 61: a          */  { 0               ,    0,    0, NULL },
/* 62: b          */  { 0               ,    0,    0, NULL },
/* 63: c          */  { 0               ,    0,    0, NULL },
/* 64: d          */  { 0               ,    0,    0, NULL },
/* 65: e          */  { 0               ,    0,    0, NULL },
/* 66: f          */  { 0               ,    0,    0, NULL },
/* 67: g          */  { 0               ,    0,    0, NULL },
/* 68: h          */  { 0               ,    0,    0, NULL },
/* 69: i          */  { 0               ,    0,    0, NULL },
/* 6a: j          */  { 0               ,    0,    0, NULL },
/* 6b: k          */  { 0               ,    0,    0, NULL },
/* 6c: l          */  { 0               ,    0,    0, NULL },
/* 6d: m          */  { 0               ,    0,    0, NULL },
/* 6e: n          */  { 0               ,    0,    0, NULL },
/* 6f: o          */  { 0               ,    0,    0, NULL },
/* 70: p          */  { 0               ,    0,    0, NULL },
/* 71: q          */  { 0               ,    0,    0, NULL },
/* 72: r          */  { 0               ,    0,    0, NULL },
/* 73: s          */  { 0               ,    0,    0, NULL },
/* 74: t          */  { 0               ,    0,    0, NULL },
/* 75: u          */  { 0               ,    0,    0, NULL },
/* 76: v          */  { 0               ,    0,    0, NULL },
/* 77: w          */  { 0               ,    0,    0, NULL },
/* 78: x          */  { 0               ,    0,    0, NULL },
/* 79: y          */  { 0               ,    0,    0, NULL },
/* 7a: z          */  { 0               ,    0,    0, NULL },
/* 7b: {          */  { F_C             ,    0,    0, do_lbrace },
/* 7c: |          */  { F_B|F_PU        ,    4,    0, op_bitor },
/* 7d: }          */  { F_C             ,    0,    0, do_rbrace },
/* 7e: ~          */  { F_U|F_PU        ,   12,    0, op_bitnot },
/* 7f: <del>      */  { 0               ,    0,    0, NULL },
#include "table2.c"
};
